export default [
  "Indicativo Presente",
  "Indicativo Imperfetto",
  "Indicativo Passato remoto",
  "Indicativo Futuro semplice",
  "Indicativo Passato prossimo",
  "Indicativo Trapassato prossimo",
  "Indicativo Trapassato remoto",
  "Indicativo Futuro anteriore",
  "Congiuntivo Presente",
  "Congiuntivo Passato",
  "Congiuntivo Imperfetto",
  "Congiuntivo Trapassato",
  "Condizionale Presente",
  "Condizionale Passato",
  "Imperativo Presente",
  "Gerundio Presente",
  "Gerundio Passato",
  "Infinito Presente",
  "Participio Presente",
  "Participio Passato"
]
