export default [
  "Indicatif Présent",
  "Indicatif Imparfait",
  "Indicatif Futur",
  "Indicatif Passé simple",
  "Indicatif Passé composé",
  "Indicatif Plus-que-parfait",
  "Indicatif Passé antérieur",
  "Indicatif Futur antérieur",
  "Subjonctif Présent",
  "Subjonctif Imparfait",
  "Subjonctif Plus-que-parfait",
  "Subjonctif Passé",
  "Conditionnel Présent",
  "Conditionnel Passé première forme",
  "Conditionnel Passé deuxième forme",
  "Participe Présent",
  "Participe Passé composé",
  "Participe Passé",
  "Impératif Présent",
  "Impératif Passé",
  "Infinitif Présent",
  "Infinitif Passé"
]
