name: Github pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Somehow required, otherwise deploy-pages@v2 fails
    permissions:
      contents: read
      pages: write
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Build website
      - name: Build website
        cwd: ${{ github.workspace }}/website
        run: |
          npm ci
          npm build
          mv ../superluminal dist/superluminal
          mv dist ../_site

      - uses: actions/upload-pages-artifact@v1
      - uses: actions/deploy-pages@v2
