name: Github pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # permissions:
    #   pages: write
    #   id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build website
      - name: Build website
        working-directory: ./website
        run: |
          npm ci
          npm run build
          mv ../superluminal dist/superluminal

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
